image: node:latest

before_script:
  - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts


stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

deploy_bobby:
  stage: deploy
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST
    - touch ideployed